APPLICATION_ENV: development

BUGSNAG_JAVASCRIPT_KEY:
BUGSNAG_RUBY_KEY:

GITHUB_WEBSITE_THEME_BRANCH:
GITHUB_WEBSITE_THEME_PATH:
GITHUB_WEBSITE_THEME_REPOSITORY:

MAIL_FROM_DEFAULT_ADDRESS:
MAIL_FROM_DEFAULT_NAME:

# Can be used when working on two incompatible branches (e.g. main & i18n)
OSUNY_DEVELOPMENT_DBNAME:

OSUNY_STAGING_APP_NAME:
OSUNY_STAGING_PG_ADDON_ID:
OSUNY_API_AUTOUPDATE_THEME_KEY:

OTP_SECRET_ENCRYPTION_KEY:

SCALEWAY_OS_ACCESS_KEY_ID:
SCALEWAY_OS_BUCKET:
SCALEWAY_OS_ENDPOINT:
SCALEWAY_OS_REGION:
SCALEWAY_OS_SECRET_ACCESS_KEY:

SECRET_KEY_BASE:

SEND_IN_BLUE_API_KEY:

SMTP_USER:
SMTP_PASSWORD:

UNSPLASH_ACCESS_KEY:
UNSPLASH_SECRET:
PEXELS_API_KEY:

DEUXFLEURS_USER: 
DEUXFLEURS_PASSWORD: 

MAINTENANCE: "false"

# Pour les tests automatis√©s
TEST_GITHUB_BRANCH:
TEST_GITHUB_ENDPOINT: '' # no use for github
TEST_GITHUB_TOKEN:
TEST_GITHUB_REPOSITORY:

TEST_GITLAB_BRANCH:
TEST_GITLAB_ENDPOINT:
TEST_GITLAB_TOKEN:
TEST_GITLAB_REPOSITORY:

